Add specs to verify #1050
When a WSDL document cannot be fetched via the new Faraday transport,
both `Savon::HTTPError#to_s` and `Savon::HTTPError#to_hash` raise a
`NoMethodError` because they call `Faraday::Response#code` instead of
`Faraday::Response#status`.

NoMethodError:
undefined method 'code' for an instance of Faraday::Response
  # ./lib/savon/http_error.rb:16:in 'Savon::HTTPError#to_s'

NoMethodError:
undefined method 'code' for an instance of Faraday::Response
  # ./lib/savon/http_error.rb:22:in 'Savon::HTTPError#to_hash'